name: GiftCode
main: NurAzliYT\GiftCode\Main
version: 1
api: [4.0.0, 5.0.0]
author: NurAzliYT
depend: BedrockEconomy

commands:
 gencode:
     description: "Generate a code"
     permission: giftcode.gencode
 redeem:
     description: use a code
