name: GiftCode
main: GiftCode\Main
version: 1
api: [3.0.0, 4.0.0]
author: Tobikiss

commands:
 gencode:
     description: "Generate a code"
     permission: giftcode.gencode
 redeem:
     description: use a code