#Hey. Thank you for using my Plugin. 
#Good Luck and enjoy it
#You can report bugs on my Discord: 
#https://discord.gg/JGvJ9RP just Ping me

#Here you can choose which character should be used.
#default= 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ.
Characters: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ

#Here you can choose the text if a player is getting rewarded.
Getting-rewarded: §f§l[§r§eGiftCode§r§f§l]§r§6§o You have successfully used a Code and got:

#Here you can choose the amount of money a Player gets for using a code. Only numbers!
Reward: 2000

#Here you can change the length of the code to whatever you want.
#only numbers. Default=4
Code-lenght: 4

#Here you can choose the text a player gets if the code is already used.
Already-used: §f§l[§r§eGiftCode§r§f§l]§r§6§o The code is already used. Try another one.

#Here you can choose the text if something went wrong.
Error: §f§l[§r§eGiftCode§r§f§l]§r§6§o Unfortunately an error happend. Please try it again.

#Here you can choose the text if someone doesnt input a code into the ui.
No-input: §f§l[§r§eGiftCode§r§f§l]§r§6§o You didn't input a code!

#here you can choose the title of the ui.
#Default= §r§f§l-=§eGiftcode Menu§r§l§f=-
ui-title: §r§f§l-=§eGiftcode Menu§r§l§f=-
#Here you can choose the text if the code couldn't be found.
Not-found: §f§l[§r§eGiftCode§r§f§l]§r§6§o The code couldn't be found. Try it again

#Here you can choose the text which you will get if you create a code
Code-created: §f§l[§r§eGiftCode§r§f§l]§r§6§o You have successfully created a code §r§f:

#here you can choose the text in the Ui.
Ui-text: Please put the code in here.

#Here you can choose which text will apear if a person without the Permission to create a code will get.
#Default=§f§l[§r§eGiftCode§r§f§l]§r§6§o You are not allowed to do that!!!
Not-Allowed: §f§l[§r§eGiftCode§r§f§l]§r§6§o You are not allowed to do that!!!